import './global.css'
import Navbar from "./_components/global/Navbar"
import CustomCursor from './_components/CustomCursor'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="body">
        <CustomCursor />
        <Navbar />
        <div className="next__app">
          {children}
        </div>
      </body>
    </html>
  )
}
